#!/usr/bin/env python3

"""Check commit message convention when new commit pushed"""

import sys
import subprocess


def print_gitlab_err_log(message):
    """print log as error on Gitlab

    Args:
        message(str): log to print
    """
    print(f"GL-HOOK-ERR: {message}")


def check_convention(oldhash, newhash):
    """check commit message convention

    Args:
        oldhash(str): old commit hash
        newhash(str): latest commit hash
    """
    result = subprocess.run(
        ["cz", "check", "--rev-range", f"{oldhash}..{newhash}"],
        capture_output=True,
        text=True,
    )
    if len(result.stderr) > 0:
        for _ in result.stderr.split("\n"):
            print_gitlab_err_log(_)
    result.check_returncode()


def main():
    """check all commit message from hook input"""

    oldhash, newhash, ref = sys.stdin.readline().split()

    try:
        check_convention(oldhash, newhash)
    except Exception:
        sys.exit(1)


if __name__ == "__main__":
    main()
